camel:
  springboot:
    name: ircc-state-persistence
    tracing: false
  rest:
    api-context-path: api
    api-component: undertow
    
server:
  address: localhost
  port: 8081

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration