camel:
  springboot:
    name: ircc-state-persistence
    tracing: false

server:
  address: localhost
  port: 8081

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration